<?php

/**
 * @author Mygento Team
 * @copyright 2023-2026 Mygento (https://www.mygento.com)
 * @package Mygento_Navigation
 */

namespace Mygento\Navigation\Model\EntityResolver;

use Magento\Catalog\Model\ResourceModel\Category\CollectionFactory;
use Magento\Framework\App\ResourceConnection;
use Mygento\Navigation\Api\EntityResolverInterface;

class Category implements EntityResolverInterface
{
    private const TABLE_URL_REWRITE = 'url_rewrite';

    public function __construct(
        private ResourceConnection $resourceConnection,
        private CollectionFactory $factory,
    ) {}

    /**
     * @param string[] $ids
     * @return array<string, string>
     */
    public function resolveName(array $ids): array
    {
        if (empty($ids)) {
            return [];
        }

        $collection = $this->factory->create();
        $collection->setStoreId(0);
        $collection->addAttributeToSelect('name');
        $collection->addFieldToFilter('entity_id', ['in' => $ids]);

        $result = [];

        foreach ($collection as $category) {
            $result[(string) $category->getId()] = sprintf(
                '[Category ID: %s] %s',
                $category->getId(),
                $category->getName(),
            );
        }

        return $result;
    }

    /**
     * @param string[] $ids
     * @return array<string, string>
     */
    public function resolveUrl(array $ids, int $storeId): array
    {
        $connection = $this->resourceConnection->getConnection();
        $select = $connection->select()
            ->from(
                ['ur' => $this->resourceConnection->getTableName(self::TABLE_URL_REWRITE)],
                ['entity_id', 'request_path'],
            )
            ->where('ur.entity_type = ?', 'category')
            ->where('ur.store_id = ?', $storeId)
            ->where('ur.redirect_type = ?', 0)
            ->where('ur.is_autogenerated = ?', 1)
            ->where('ur.metadata IS NULL')
            ->where('ur.entity_id IN (?)', $ids)
            ->order('ur.url_rewrite_id ASC');

        return $connection->fetchPairs($select);
    }
}
