<?php

/**
 * @author Mygento Team
 * @copyright 2023-2026 Mygento (https://www.mygento.com)
 * @package Mygento_Navigation
 */

namespace Mygento\Navigation\Model\EntityResolver;

use Magento\Cms\Model\ResourceModel\Page\CollectionFactory;
use Magento\Framework\App\ResourceConnection;
use Mygento\Navigation\Api\EntityResolverInterface;

class Page implements EntityResolverInterface
{
    private const TABLE_URL_REWRITE = 'url_rewrite';

    public function __construct(
        private ResourceConnection $resourceConnection,
        private CollectionFactory $factory,
    ) {}

    public function resolveName(array $ids): array
    {
        if (empty($ids)) {
            return [];
        }

        $collection = $this->factory->create();
        $collection->addFieldToFilter(
            'page_id',
            ['in' => $ids],
        );
        $collection->addFieldToSelect(['page_id', 'title']);

        $result = [];

        foreach ($collection as $page) {
            $result[(string) $page->getId()] = sprintf(
                '[Page ID: %s] %s',
                $page->getId(),
                $page->getTitle(),
            );
        }

        return $result;
    }

    /**
     * @param string[] $ids
     * @return array<string, string>
     */
    public function resolveUrl(array $ids, int $storeId): array
    {
        $connection = $this->resourceConnection->getConnection();
        $select = $connection->select()
            ->from(
                ['ur' => $this->resourceConnection->getTableName(self::TABLE_URL_REWRITE)],
                ['entity_id', 'request_path'],
            )
            ->where('ur.entity_type = ?', 'cms-page')
            ->where('ur.store_id = ?', $storeId)
            ->where('ur.redirect_type = ?', 0)
            ->where('ur.is_autogenerated = ?', 1)
            ->where('ur.metadata IS NULL')
            ->where('ur.entity_id IN (?)', $ids)
            ->order('ur.url_rewrite_id ASC');

        return $connection->fetchPairs($select);
    }
}
