type NavigationMenuItem @doc(description: "Item") {
    entity_identifier: String @doc(description: "Target Entity ID")
    entity_type: String! @doc(description: "Entity Type")
    sort_order: Int! @doc(description: "Item Sort Order")
    name: String! @doc(description: "Item name")
    link: String @doc(description: "Link")
    image: String @doc(description: "Item image")
}

type Query {
    navigationMenu(
        code: String!,
    ): NavigationMenu @resolver(class: "Mygento\\Navigation\\Model\\Resolver\\NavigationMenu")
}

type NavigationMenu {
    code: String!
    items: [NavigationMenuItem!] @doc(description: "List of items in menu")
}
